#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

myynh_prepare_source

#=================================================
# MAKE INSTALL
#=================================================
ynh_script_progression "Making install..."

myynh_install_searxng

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

secret_key=$(ynh_string_random)
ynh_config_add --template="settings.yml" \
	--destination="$install_dir/settings.yml"
ynh_config_add --template="$install_dir/searxng-src/searx/limiter.toml" \
	--destination="$install_dir/limiter.toml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="SearXNG metasearch engine" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

myynh_set_permissions

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
