#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if [ -e "$install_dir/searx" ]; then
	tempdir="$(mktemp -d)"
	mv "$install_dir/searx/settings.yml" "$tempdir/settings.yml"
	sed -i '1s/^/use_default_settings: true\n\n/' "$tempdir/settings.yml"
	ynh_safe_rm "$install_dir"
	mkdir "$install_dir"
	mv "$tempdir/settings.yml" "$install_dir/settings.yml"
	ynh_safe_rm "$tempdir"
	ynh_store_file_checksum "$install_dir/settings.yml"
	ynh_delete_file_checksum "/opt/yunohost/$app/searx/settings.yml"
fi
if ynh_app_upgrading_from_version_before 2026.01.02~ynh1
then
	# Remove the uwsgi config
	yunohost service remove "uwsgi-app@$app"
	ynh_systemctl --service="uwsgi-app@$app.service" --action="stop"
	ynh_systemctl --service="uwsgi-app@$app.service" --action="disable"
	ynh_safe_rm "/etc/uwsgi/apps-available/$app.ini"
	ynh_safe_rm "/var/log/uwsgi/$app"
	ynh_safe_rm "/etc/systemd/system/uwsgi-app@$app.service"
	ynh_safe_rm "/etc/systemd/system/uwsgi-app@$app.service.d"
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="app.service" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_safe_rm "$install_dir/.profile"
ynh_safe_rm "$install_dir/.cache"
ynh_safe_rm "$install_dir/searxng-src"
ynh_safe_rm "$install_dir/searxng-pyenv"
myynh_prepare_source

#=================================================
# MAKE INSTALL
#=================================================
ynh_script_progression "Making install..."

myynh_install_searxng

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

if [ ! -e "$install_dir/limiter.toml" ]; then
	ynh_config_add --template="$install_dir/searxng-src/searx/limiter.toml" \
		--destination="$install_dir/limiter.toml"
fi

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add --template="systemd.socket" --destination="/etc/systemd/system/$app.socket"
ynh_config_add_systemd
yunohost service add "$app" --description="SearXNG metasearch engine" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

myynh_set_permissions

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app.service" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
