#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if [ -e "$install_dir/searx" ]; then
	tempdir="$(mktemp -d)"
	mv "$install_dir/searx/settings.yml" "$tempdir/settings.yml"
	sed -i '1s/^/use_default_settings: true\n\n/' "$tempdir/settings.yml"
	ynh_safe_rm "$install_dir"
	mkdir "$install_dir"
	mv "$tempdir/settings.yml" "$install_dir/settings.yml"
	ynh_safe_rm "$tempdir"
	ynh_store_file_checksum "$install_dir/settings.yml"
	ynh_delete_file_checksum "/opt/yunohost/$app/searx/settings.yml"
fi

ynh_delete_file_checksum "etc/nginx_conf.d/$domain/$app.conf"

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="uwsgi-app@$app.service" \
	--action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_safe_rm "$install_dir/.profile"
ynh_safe_rm "$install_dir/.cache"
ynh_safe_rm "$install_dir/searxng-src"
ynh_safe_rm "$install_dir/searxng-pyenv"
mkdir "$install_dir/searxng-src"
ynh_setup_source --dest_dir="$install_dir/searxng-src"

#=================================================
# MAKE INSTALL
#=================================================
ynh_script_progression "Making install..."

myynh_install_searxng

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

if [ ! -e "$install_dir/limiter.toml" ]; then
	ynh_config_add --template="$install_dir/searxng-src/searx/limiter.toml" \
		--destination="$install_dir/limiter.toml"
fi

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_add_uwsgi_service

myynh_set_permissions

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="uwsgi-app@$app.service" \
	--action="start" \
	--wait_until="WSGI app 0 \(mountpoint='[/[:alnum:]_-]*'\) ready in [[:digit:]]* seconds on interpreter" \
	--log_path="/var/log/uwsgi/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
